version: "3.9"
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: pimis
      RABBITMQ_PASSWORD: pimis
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    ports:
      - "15672:15672"
  db:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: prod.dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
volumes:
  static: { }
  media: { }
  database_data: { }
