# Generated by Django 5.0.3 on 2024-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_cerificate', models.FileField(upload_to='files/2024/3/14')),
                ('national_id', models.FileField(upload_to='files/2024/3/14')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_application_for_someone_else', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Passport', 'Passport'), ('ID', 'ID')], max_length=45)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Application Received', 'Application Received'), ('Application Rejected', 'Application Rejected'), ('Appointment Scheduled', 'Appointment Scheduled'), ('Processing', 'Processing'), ('Ready For Collection', 'Ready For Collection')], max_length=45)),
                ('street', models.CharField(max_length=150)),
                ('suburb', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
