# Generated by Django 5.0.3 on 2024-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_applicantdetails_birth_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.FileField(blank=True, null=True, upload_to='results/')),
                ('actual', models.FileField(blank=True, null=True, upload_to='results/')),
                ('forecast', models.FileField(blank=True, null=True, upload_to='results/')),
                ('actual_prediction', models.FileField(blank=True, null=True, upload_to='results/')),
            ],
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='birth_certificate',
            field=models.FileField(upload_to='files/2024/12/12'),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='national_id',
            field=models.FileField(upload_to='files/2024/12/12'),
        ),
    ]
