# Generated by Django 5.0.3 on 2024-03-15 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_application_city_remove_application_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantdetails',
            old_name='birth_cerificate',
            new_name='birth_certificate',
        ),
        migrations.AddField(
            model_name='applicantdetails',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Application Received', 'Application Received'), ('Application Rejected', 'Application Rejected'), ('Appointment Scheduled', 'Appointment Scheduled'), ('Processing', 'Processing'), ('Ready For Collection', 'Ready For Collection'), ('Application Completed', 'Application Completed')], default='Pending', max_length=45),
        ),
    ]
