# Generated by Django 5.0.3 on 2024-12-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionjob',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='birth_certificate',
            field=models.FileField(upload_to='files/2024/12/30'),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='national_id',
            field=models.FileField(upload_to='files/2024/12/30'),
        ),
    ]
