# Generated by Django 5.0.3 on 2024-03-18 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointment_end_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Lorem', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='birth_certificate',
            field=models.FileField(upload_to='files/2024/3/18'),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='national_id',
            field=models.FileField(upload_to='files/2024/3/18'),
        ),
    ]
