# Generated by Django 5.0.3 on 2024-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_appointment_date_appointment_appointment_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paynow_poll_url',
            field=models.CharField(default='http://example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paynow_redirect_url',
            field=models.CharField(default='http://example.com', max_length=255),
            preserve_default=False,
        ),
    ]
