# Generated by Django 5.0.3 on 2024-03-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_paynow_poll_url_payment_paynow_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paynow_poll_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paynow_redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
