# Generated by Django 5.0.3 on 2024-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_appointment_end_datetime_appointment_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='birth_certificate',
            field=models.FileField(upload_to='files/2024/6/14'),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='national_id',
            field=models.FileField(upload_to='files/2024/6/14'),
        ),
    ]
